- name: Publish NuGet
  uses: rohith/publish-nuget@v1.2.0
  with:
    # Project (csproj) directory path relative from the root of repository
    project_dir: ./XIL
    nuget_key: ${{secrets.XIL_NUGET}}
