name: Publish NuGet
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: [ubuntu-latest]
    steps:
    - run: pwd | cat
    - uses: rohith/publish-nuget@v1.2.0
      with:
        project_dir: XIL
        nuget_key: ${{secrets.XIL_NUGET}}
